;list of animated block textures
;First is file name, second is (minified) json that needs to be written

Global $blast_furnace_front_on[2] = ["blast_furnace_front_on.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $campfire_fire[2] = ["campfire_fire.png", '{"animation":{"frametime":2}}']
Global $campfire_log_lit[2] = ["campfire_log_lit.png", '{"animation":{"interpolate":true,"frametime":20}}']
Global $chain_command_block_back[2] = ["chain_command_block_back.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $chain_command_block_conditional[2] = ["chain_command_block_conditional.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $chain_command_block_front[2] = ["chain_command_block_front.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $chain_command_block_side[2] = ["chain_command_block_side.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $command_block_back[2] = ["command_block_back.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $command_block_conditional[2] = ["command_block_conditional.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $command_block_front[2] = ["command_block_front.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $command_block_side[2] = ["command_block_side.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $crimson_stem[2] = ["crimson_stem.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $fire_0[2] = ["fire_0.png", '{"animation":{"frames":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]}}']
Global $fire_1[2] = ["fire_1.png", '{"animation":{}}']
Global $kelp[2] = ["kelp.png", '{"animation":{"frametime":2}}']
Global $kelp_plant[2] = ["kelp_plant.png", '{"animation":{"frametime":2}}']
Global $lantern[2] = ["lantern.png", '{"animation":{"frametime":8}}']
Global $lava_flow[2] = ["lava_flow.png", '{"animation":{"frametime":3}}']
Global $lava_still[2] = ["lava_still.png", '{"animation":{"frametime":2,"frames":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1]}}']
Global $magma[2] = ["magma.png", '{"animation":{"frametime":8,"interpolate":true,"frames":[0,1,2]}}']
Global $nether_portal[2] = ["nether_portal.png", '{"animation":{}}']
Global $prismarine[2] = ["prismarine.png", '{"animation":{"frametime":300,"interpolate":true,"frames":[0,1,0,2,0,3,0,1,2,1,3,1,0,2,1,2,3,2,0,3,1,3]}}']
Global $repeating_command_block_back[2] = ["repeating_command_block_back.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $repeating_command_block_conditional[2] = ["repeating_command_block_conditional.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $repeating_command_block_front[2] = ["repeating_command_block_front.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $repeating_command_block_side[2] = ["repeating_command_block_side.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $respawn_anchor_top[2] = ["respawn_anchor_top.png", '{"animation":{}}']
Global $sculk[2] = ["sculk.png", '{"animation":{"frametime":20,"interpolate":true}}']
Global $sculk_catalyst_side_bloom[2] = ["sculk_catalyst_side_bloom.png", '{"animation":{"frametime":1}}']

Global $sculk_catalyst_top_bloom[2] = ["sculk_catalyst_top_bloom.png", '{"animation":{"frametime":1}}']
Global $sculk_sensor_tendril_active[2] = ["sculk_sensor_tendril_active.png", '{"animation":{"frametime":1}}']
Global $sculk_sensor_tendril_inactive[2] = ["sculk_sensor_tendril_inactive.png", '{"animation":{"frametime":2}}']
Global $sculk_shrieker_can_summon_inner_top[2] = ["sculk_shrieker_can_summon_inner_top.png", '{"animation":{"frametime":3,"interpolate":true}}']
Global $sculk_shrieker_inner_top[2] = ["sculk_shrieker_inner_top.png", '{"animation":{"frametime":6,"interpolate":true}}']
Global $sculk_vein[2] = ["sculk_vein.png", '{"animation":{"frametime":20,"interpolate":true}}']
Global $seagrass[2] = ["seagrass.png", '{"animation":{"frametime":2}}']
Global $sea_lantern[2] = ["sea_lantern.png", '{"animation":{"frametime":5}}']
Global $smoker_front_on[2] = ["smoker_front_on.png", '{"animation":{"interpolate":false,"frametime":4}}']
Global $soul_campfire_fire[2] = ["soul_campfire_fire.png", '{"animation":{"frametime":2}}']
Global $soul_campfire_log_lit[2] = ["soul_campfire_log_lit.png", '{"animation":{"interpolate":true,"frametime":20}}']
Global $soul_fire_0[2] = ["soul_fire_0.png", '{"animation":{"frames":[16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]}}']
Global $soul_fire_1[2] = ["soul_fire_1.png", '{"animation":{}}']
Global $soul_lantern[2] = ["soul_lantern.png", '{"animation":{"frametime":8}}']
Global $stonecutter_saw[2] = ["stonecutter_saw.png", '{"animation":{"interpolate":false,"frametime":1}}']
Global $tall_seagrass_bottom[2] = ["tall_seagrass_bottom.png", '{"animation":{"frametime":2}}']
Global $tall_seagrass_top[2] = ["tall_seagrass_top.png", '{"animation":{"frametime":2}}']
Global $warped_stem[2] = ["warped_stem.png", '{"animation":{"interpolate":true,"frametime":10}}']
Global $water_flow[2] = ["water_flow.png", '{"animation":{}}']
Global $water_still[2] = ["water_still.png", '{"animation":{"frametime":2}}']

Global $animeTextures1[26] = [$blast_furnace_front_on, $campfire_fire, $campfire_log_lit, $chain_command_block_back, $chain_command_block_conditional, $chain_command_block_front, $chain_command_block_side, $crimson_stem, $fire_0, $fire_1, $kelp, $kelp_plant, $lantern, $lava_flow, $lava_still, $lava_still, $magma, $nether_portal, $prismarine, $repeating_command_block_back, $repeating_command_block_conditional, $repeating_command_block_front, $repeating_command_block_side, $respawn_anchor_top, $sculk, $sculk_catalyst_side_bloom]

Global $animeTextures2[20] = [$sculk_catalyst_top_bloom, $sculk_sensor_tendril_active, $sculk_sensor_tendril_inactive, $sculk_shrieker_can_summon_inner_top, $sculk_shrieker_inner_top, $sculk_vein, $seagrass, $sea_lantern, $smoker_front_on, $soul_campfire_fire, $soul_campfire_log_lit, $soul_fire_0, $soul_fire_1, $soul_lantern, $stonecutter_saw, $tall_seagrass_bottom, $tall_seagrass_top, $warped_stem, $water_flow, $water_still]
