;Color map textures
Global $foliage_colormap[2] = ["textures\colormap\foliage.png", "assets\minecraft\textures\colormap\foliage.png"]
Global $grass_colormap[2] = ["textures\colormap\grass.png", "assets\minecraft\textures\colormap\grass.png"]

Global $colorMapTextures[2] = [$foliage_colormap, $grass_colormap]

;Environment Textures
Global $clouds[2] = ["textures\environment\clouds.png", "assets\minecraft\textures\environment\clouds.png"]
Global $moon_phases[2] = ["textures\environment\moon_phases.png", "assets\minecraft\textures\environment\moon_phases.png"]
Global $sun[2] = ["textures\environment\sun.png", "assets\minecraft\textures\environment\sun.png"]
Global $destroy_stage_1[2] = ["textures\environment\destroy_stage_1.png", "assets\minecraft\textures\block\destroy_stage_1.png"]
Global $destroy_stage_2[2] = ["textures\environment\destroy_stage_2.png", "assets\minecraft\textures\block\destroy_stage_2.png"]
Global $destroy_stage_3[2] = ["textures\environment\destroy_stage_3.png", "assets\minecraft\textures\block\destroy_stage_3.png"]
Global $destroy_stage_4[2] = ["textures\environment\destroy_stage_4.png", "assets\minecraft\textures\block\destroy_stage_4.png"]
Global $destroy_stage_5[2] = ["textures\environment\destroy_stage_5.png", "assets\minecraft\textures\block\destroy_stage_5.png"]
Global $destroy_stage_6[2] = ["textures\environment\destroy_stage_6.png", "assets\minecraft\textures\block\destroy_stage_6.png"]
Global $destroy_stage_7[2] = ["textures\environment\destroy_stage_7.png", "assets\minecraft\textures\block\destroy_stage_7.png"]
Global $destroy_stage_8[2] = ["textures\environment\destroy_stage_8.png", "assets\minecraft\textures\block\destroy_stage_8.png"]
Global $destroy_stage_9[2] = ["textures\environment\destroy_stage_9.png", "assets\minecraft\textures\block\destroy_stage_9.png"]

Global $environmentTextures[12] = [$clouds, $moon_phases, $sun, $destroy_stage_1, $destroy_stage_2, $destroy_stage_3, $destroy_stage_4, $destroy_stage_5, $destroy_stage_6, $destroy_stage_7, $destroy_stage_8, $destroy_stage_9]

;arnor textures
Global $chain_1[2] = ["textures\models\armor\chain_1.png", "assets\minecraft\textures\models\armor\chainmail_layer_1.png"]
Global $chain_2[2] = ["textures\models\armor\chain_2.png", "assets\minecraft\textures\models\armor\chainmail_layer_2.png"]
Global $diamond_1[2] = ["textures\models\armor\diamond_1.png", "assets\minecraft\textures\models\armor\diamond_layer_1.png"]
Global $diamond_2[2] = ["textures\models\armor\diamond_2.png", "assets\minecraft\textures\models\armor\diamond_layer_2.png"]
Global $gold_1[2] = ["textures\models\armor\gold_1.png", "assets\minecraft\textures\models\armor\gold_layer_1.png"]
Global $gold_2[2] = ["textures\models\armor\gold_2.png", "assets\minecraft\textures\models\armor\gold_layer_2.png"]
Global $iron_1[2] = ["textures\models\armor\iron_1.png", "assets\minecraft\textures\models\armor\iron_layer_1.png"]
Global $iron_2[2] = ["textures\models\armor\iron_2.png", "assets\minecraft\textures\models\armor\iron_layer_2.png"]
Global $netherite_1[2] = ["textures\models\armor\netherite_1.png", "assets\minecraft\textures\models\armor\netherite_layer_1.png"]
Global $netherite_2[2] = ["textures\models\armor\netherite_2.png", "assets\minecraft\textures\models\armor\netherite_layer_2.png"]
Global $turtle_1[2] = ["textures\models\armor\turtle_1.png", "assets\minecraft\textures\models\armor\turtle_layer_1.png"]


Global $armorTextures[11] = [$chain_1, $chain_2, $diamond_1, $diamond_2, $gold_1, $gold_2, $iron_1, $iron_2, $netherite_1, $netherite_2, $turtle_1]

;GUI textures
Global $icons[2] = ["textures\gui\icons.png", "assets\minecraft\textures\gui\icons.png"]
Global $panorama_0[2] = ["textures\ui\panorama_0.png", "assets\minecraft\textures\gui\title\background\panorama_0.png"]
Global $panorama_1[2] = ["textures\ui\panorama_1.png", "assets\minecraft\textures\gui\title\background\panorama_1.png"]
Global $panorama_2[2] = ["textures\ui\panorama_2.png", "assets\minecraft\textures\gui\title\background\panorama_2.png"]
Global $panorama_3[2] = ["textures\ui\panorama_3.png", "assets\minecraft\textures\gui\title\background\panorama_3.png"]
Global $panorama_4[2] = ["textures\ui\panorama_4.png", "assets\minecraft\textures\gui\title\background\panorama_4.png"]
Global $panorama_5[2] = ["textures\ui\panorama_5.png", "assets\minecraft\textures\gui\title\background\panorama_5.png"]
Global $panorama_overlay = ["textures\ui\panorama_overlay.png", "assets\minecraft\textures\gui\title\background\panorama_overlay.png"]

Global $guiTextures[8] = [$icons, $panorama_0, $panorama_1, $panorama_2, $panorama_3, $panorama_4, $panorama_5, $panorama_overlay]

;Trim Textures
Global $amethyst[2] = ["textures\trims\color_palettes\amethyst.png", "assets\minecraft\textures\trims\color_palettes\amethyst.png"]
Global $copper[2] = ["textures\trims\color_palettes\copper.png", "assets\minecraft\textures\trims\color_palettes\copper.png"]
Global $diamond[2] = ["textures\trims\color_palettes\diamond.png", "assets\minecraft\textures\trims\color_palettes\diamond.png"]
Global $diamond_darker[2] = ["textures\trims\color_palettes\diamond_darker.png", "assets\minecraft\textures\trims\color_palettes\diamond_darker.png"]
Global $emerald[2] = ["textures\trims\color_palettes\emerald.png", "assets\minecraft\textures\trims\color_palettes\emerald.png"]
Global $gold[2] = ["textures\trims\color_palettes\gold.png", "assets\minecraft\textures\trims\color_palettes\gold.png"]
Global $gold_darker[2] = ["textures\trims\color_palettes\gold_darker.png", "assets\minecraft\textures\trims\color_palettes\gold_darker.png"]
Global $iron[2] = ["textures\trims\color_palettes\iron.png", "assets\minecraft\textures\trims\color_palettes\iron.png"]
Global $iron_darker[2] = ["textures\trims\color_palettes\iron_darker.png", "assets\minecraft\textures\trims\color_palettes\iron_darker.png"]
Global $lapis[2] = ["textures\trims\color_palettes\lapis.png", "assets\minecraft\textures\trims\color_palettes\lapis.png"]
Global $netherite[2] = ["textures\trims\color_palettes\netherite.png", "assets\minecraft\textures\trims\color_palettes\netherite.png"]
Global $netherite_darker[2] = ["textures\trims\color_palettes\netherite_darker.png", "assets\minecraft\textures\trims\color_palettes\netherite_darker.png"]
Global $quartz[2] = ["textures\trims\color_palettes\quartz.png", "assets\minecraft\textures\trims\color_palettes\quartz.png"]
Global $redstone[2] = ["textures\trims\color_palettes\redstone.png", "assets\minecraft\textures\trims\color_palettes\redstone.png"]
Global $trim_palette[2] = ["textures\trims\color_palettes\trim_palette.png", "assets\minecraft\textures\trims\color_palettes\trim_palette.png"]
Global $boots_trim[2] = ["textures\trims\items\boots_trim.png", "assets\minecraft\textures\trims\items\boots_trim.png"]
Global $chestplate_trim[2] = ["textures\trims\items\chestplate_trim.png", "assets\minecraft\textures\trims\items\chestplate_trim.png"]
Global $helmet_trim[2] = ["textures\trims\items\helmet_trim.png", "assets\minecraft\textures\trims\items\helmet_trim.png"]
Global $leggings_trim[2] = ["textures\trims\items\leggings_trim.png", "assets\minecraft\textures\trims\items\leggings_trim.png"]
Global $coast[2] = ["textures\trims\coast.png", "assets\minecraft\textures\trims\models\armor\coast.png"]
Global $coast_leggings[2] = ["textures\trims\coast_leggings.png", "assets\minecraft\textures\trims\models\armor\coast_leggings.png"]
Global $dune[2] = ["textures\trims\dune.png", "assets\minecraft\textures\trims\models\armor\dune.png"]
Global $dune_leggings[2] = ["textures\trims\dune_leggings.png", "assets\minecraft\textures\trims\models\armor\dune_leggings.png"]
Global $eye[2] = ["textures\trims\eye.png", "assets\minecraft\textures\trims\models\armor\eye.png"]
Global $eye_leggings[2] = ["textures\trims\eye_leggings.png", "assets\minecraft\textures\trims\models\armor\eye_leggings.png"]
Global $host[2] = ["textures\trims\host.png", "assets\minecraft\textures\trims\models\armor\host.png"]
Global $host_leggings[2] = ["textures\trims\host_leggings.png", "assets\minecraft\textures\trims\models\armor\host_leggings.png"]
Global $raiser[2] = ["textures\trims\raiser.png", "assets\minecraft\textures\trims\models\armor\raiser.png"]
Global $raiser_leggings[2] = ["textures\trims\raiser_leggings.png", "assets\minecraft\textures\trims\models\armor\raiser_leggings.png"]
Global $rib[2] = ["textures\trims\rib.png", "assets\minecraft\textures\trims\models\armor\rib.png"]
Global $rib_leggings[2] = ["textures\trims\rib_leggings.png", "assets\minecraft\textures\trims\models\armor\rib_leggings.png"]
Global $sentry[2] = ["textures\trims\sentry.png", "assets\minecraft\textures\trims\models\armor\sentry.png"]
Global $sentry_leggings[2] = ["textures\trims\sentry_leggings.png", "assets\minecraft\textures\trims\models\armor\sentry_leggings.png"]
Global $shaper[2] = ["textures\trims\shaper.png", "assets\minecraft\textures\trims\models\armor\shaper.png"]
Global $shaper_leggings[2] = ["textures\trims\shaper_leggings.png", "assets\minecraft\textures\trims\models\armor\shaper_leggings.png"]
Global $silence[2] = ["textures\trims\silence.png", "assets\minecraft\textures\trims\models\armor\silence.png"]
Global $silence_leggings[2] = ["textures\trims\silence_leggings.png", "assets\minecraft\textures\trims\models\armor\silence_leggings.png"]
Global $snout[2] = ["textures\trims\snout.png", "assets\minecraft\textures\trims\models\armor\snout.png"]
Global $snout_leggings[2] = ["textures\trims\snout_leggings.png", "assets\minecraft\textures\trims\models\armor\snout_leggings.png"]
Global $spire[2] = ["textures\trims\spire.png", "assets\minecraft\textures\trims\models\armor\spire.png"]
Global $spire_leggings[2] = ["textures\trims\spire_leggings.png", "assets\minecraft\textures\trims\models\armor\spire_leggings.png"]
Global $tide[2] = ["textures\trims\tide.png", "assets\minecraft\textures\trims\models\armor\tide.png"]
Global $tide_leggings[2] = ["textures\trims\tide_leggings.png", "assets\minecraft\textures\trims\models\armor\tide_leggings.png"]
Global $vex[2] = ["textures\trims\vex.png", "assets\minecraft\textures\trims\models\armor\vex.png"]
Global $vex_leggings[2] = ["textures\trims\vex_leggings.png", "assets\minecraft\textures\trims\models\armor\vex_leggings.png"]
Global $ward[2] = ["textures\trims\ward.png", "assets\minecraft\textures\trims\models\armor\ward.png"]
Global $ward_leggings[2] = ["textures\trims\ward_leggings.png", "assets\minecraft\textures\trims\models\armor\ward_leggings.png"]
Global $wayfinder[2] = ["textures\trims\wayfinder.png", "assets\minecraft\textures\trims\models\armor\wayfinder.png"]
Global $wayfinder_leggings[2] = ["textures\trims\wayfinder_leggings.png", "assets\minecraft\textures\trims\models\armor\wayfinder_leggings.png"]
Global $wild[2] = ["textures\trims\wild.png", "assets\minecraft\textures\trims\models\armor\wild.png"]
Global $wild_leggings[2] = ["textures\trims\wild_leggings.png", "assets\minecraft\textures\trims\models\armor\wild_leggings.png"]

Global $trimTextures[48] = [$amethyst, $copper, $diamond, $diamond_darker, $emerald, $gold, $gold_darker, $iron, $iron_darker, $lapis, $netherite, $netherite_darker, $quartz, $redstone, $trim_palette, $boots_trim, $chestplate_trim, $helmet_trim, $leggings_trim, $coast, $coast_leggings, $dune, $dune_leggings, $eye, $eye_leggings, $host, $host_leggings, $raiser, $raiser_leggings, $rib, $rib_leggings, $sentry_leggings, $shaper, $shaper_leggings, $silence, $silence_leggings, $spire, $spire_leggings, $tide, $tide_leggings, $vex, $vex_leggings, $ward, $ward_leggings, $wayfinder, $wayfinder_leggings, $wild, $wild_leggings]